// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8PvmFoeyCx1nSX8DdMlVAxKSkR2l_eg4',
    appId: '1:253533636338:web:ce8aebda0d99500982b26b',
    messagingSenderId: '253533636338',
    projectId: 'sggc-21ac7',
    authDomain: 'sggc-21ac7.firebaseapp.com',
    storageBucket: 'sggc-21ac7.firebasestorage.app',
    measurementId: 'G-PLBKZ85HZE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkJ7AdFouhFlF3N6nvPl9FgXe6rACvHcU',
    appId: '1:253533636338:android:e7ad0223a1d925f982b26b',
    messagingSenderId: '253533636338',
    projectId: 'sggc-21ac7',
    storageBucket: 'sggc-21ac7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2NdBP0xDsfs8Vhy0f0fMF_BpjAiiPagQ',
    appId: '1:253533636338:ios:4780f13a8783a1d882b26b',
    messagingSenderId: '253533636338',
    projectId: 'sggc-21ac7',
    storageBucket: 'sggc-21ac7.firebasestorage.app',
    iosBundleId: 'com.example.sticampuscentralguide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2NdBP0xDsfs8Vhy0f0fMF_BpjAiiPagQ',
    appId: '1:253533636338:ios:4780f13a8783a1d882b26b',
    messagingSenderId: '253533636338',
    projectId: 'sggc-21ac7',
    storageBucket: 'sggc-21ac7.firebasestorage.app',
    iosBundleId: 'com.example.sticampuscentralguide',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8PvmFoeyCx1nSX8DdMlVAxKSkR2l_eg4',
    appId: '1:253533636338:web:c6e0ff36a8eedca682b26b',
    messagingSenderId: '253533636338',
    projectId: 'sggc-21ac7',
    authDomain: 'sggc-21ac7.firebaseapp.com',
    storageBucket: 'sggc-21ac7.firebasestorage.app',
    measurementId: 'G-BLRJMKQ60F',
  );
}
